
<div class="container w-50">

<form method="post" enctype="multipart/form-data"  action="#">

    <div class="form-group">
        <label for="mediaType">Media type</label>
        <input type="text" name="type" class="form-control" id="mediaType" aria-describedby="mediaHelp" placeholder="type of media">
        <small id="mediaHelp" class="form-text text-muted">Media type (CD, VIDEO, ....)</small>
    </div>
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title" class="form-control" id="title" placeholder="title">
    </div>
    <div class="form-group">
        <label for="interpreter">Interpreter</label>
        <input type="text" name="interpreter" class="form-control" id="interpreter" placeholder="interpreter">
    </div>
    <div class="form-group">
        <label for="genre">Genre</label>
        <input type="text" name="genre" class="form-control" id="genre" placeholder="genre">
    </div>

    <div class="form-group">
        <label for="genre">File</label>
        <input name="mediafile" type="file" />
    </div>

    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

</div>
