
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Add new Album example</h1>
                <p>
                    <a href="#" class="btn btn-primary my-2">Main call to action</a>
                    <a href="#" class="btn btn-secondary my-2">Secondary action</a>
                </p>
            </div>
        </div>
    </section>




<form method="post" enctype="multipart/form-data"  action="#">


    <div class="container w-100">

    <div class="row">

        <div class="col">

        <div class="card-header">

            <div class="form-group">
                <label for="mediaType">media type</label>
                <input type="text" name="type" class="form-control" id="mediaType" aria-describedby="mediaHelp" placeholder="type of media" required>
                <small id="mediaHelp" class="form-text text-muted">Media type (CD, VIDEO, ....)</small>
            </div>
            <div class="form-group">
                <label for="title">title</label>
                <input type="text" name="title" class="form-control" id="title" placeholder="title" required>
            </div>
            <div class="form-group">
                <label for="interpreter">interpreter</label>
                <input type="text" name="interpreter" class="form-control" id="interpreter" placeholder="interpreter" required>
            </div>
            <div class="form-group">
                <label for="genre">genre</label>
                <input type="text" name="genre" class="form-control" id="genre" placeholder="genre" required>
            </div>

            <div class="form-group">
                <label for="file">file</label>
                <input name="mediafile" type="file" class="form-control" >
            </div>

            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Active</label>
            </div>
        </div>
        </div>

        <div class="col">

        <div class="card-body" style="background-color: rgba(0,0,0,.03);">
            <div class="form-group;" >
                <label for="title">title_1</label>
                <input type="text" name="playlist_title[]" class="form-control title"  placeholder="title-1">
                <label for="duration">duration_1</label>
                <input type="text" name="playlist_duration[]" class="form-control duration"  placeholder="duration-1">
            </div>

            <button type="button" name="add-new-title" class="btn bg-secondary" >Add new title</button>
        </div>
        </div>

    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

    </div>

</form>



</main>