
<div class="container w-50">

    <form method="post" enctype="multipart/form-data"  action="#">

        <div class="">
            <img class="mr-3"  style="max-width: 200px;" src="../../public/images/<?=$this->viewData['mediaData']->getImage()?>" alt="Generic placeholder image" />

            <div class="form-group">
                <label for="genre">File</label>
                <input name="mediafile" type="file" />
            </div>
        </div>

        <div class="">
            <div class="form-group">
                <label for="title">ID</label>
                <input type="text" name="id" class="form-control" id="id" placeholder="title" value="<?=$this->viewData['mediaData']->getId()?>">
            </div>

            <div class="form-group">
                <label for="mediaType">Media type</label>
                <input type="text" name="type" class="form-control" id="mediaType" aria-describedby="mediaHelp" placeholder="type of media" value="<?=$this->viewData['mediaData']->getType()?>">
                <small id="mediaHelp" class="form-text text-muted">Media type (CD, VIDEO, ....)</small>
            </div>
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" name="title" class="form-control" id="title" placeholder="title" value="<?=$this->viewData['mediaData']->getTitle()?>">
            </div>
            <div class="form-group">
                <label for="interpreter">Interpreter</label>
                <input type="text" name="interpreter" class="form-control" id="interpreter" placeholder="interpreter" value="<?=$this->viewData['mediaData']->getInterpreter()?>">
            </div>
            <div class="form-group">
                <label for="genre">Genre</label>
                <input type="text" name="genre" class="form-control" id="genre" placeholder="genre" value="<?=$this->viewData['mediaData']->getGenre()?>">
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</div>
