<ul class="list-group list-group-flush">

    <li class="list-group-item">
        Logged in User: {username}
    </li>

    <li class="list-group-item">
        <a href="media/add"> Add new media item </a>
    </li>

    <li class="list-group-item">
        <a href="">Albums</a>
    </li>
    <li class="list-group-item">
        Artists
    </li>
    <li class="list-group-item">
        Playlists
    </li>
    <li class="list-group-item">
        Popular Tracks
    </li>
</ul>

