

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Album example</h1>
                <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
                <p>
                    <a href="#" class="btn btn-primary my-2">Main call to action</a>
                    <a href="#" class="btn btn-secondary my-2">Secondary action</a>
                </p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

                <?php

                $Paginator = $this->viewData['Paginator'];
                $data = $Paginator->current();

                foreach ($data as $key2 => $dt) {?>

                <div class="col">
                    <div class="card shadow-sm">
                        <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="public/images/<?=$dt->getImage()?>">

                        <div class="card-body">
                            <p class="card-header"><?=$dt->getInterpreter()?>

                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>


                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">

                                    <a href="media/edit/<?=$dt->getId()?>" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Edit</a>
                                    <a href="media/view/<?=$dt->getId()?>" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">View</a>
                                    <a href="media/delete/<?=$dt->getId();?>" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Delete</a>

                                </div>
                                <small class="text-muted">10 mins</small>
                            </div>
                        </div>
                    </div>
                </div>

                <?php } ?>

            </div>


            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="prev-item page-item"><a class="page-link prev" href="<?=$Paginator->prev()?>">Previous</a></li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="next-item page-item"><a class="page-link next" href="<?=$Paginator->next();?>">Next</a></li>
                </ul>
            </nav>

        </div>
    </div>

</main>

