
<main>
    <section class="py-1 text-center container">
        <div class="row py-lg-1">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">CD Media</h1>
                <p>
                    <a href="#" class="btn btn-primary my-2">Artists</a>
                    <a href="#" class="btn btn-secondary my-2">Albums</a>
                </p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <?php

                $Paginator = $this->viewData['Paginator'];
                $data = $Paginator->current();

                foreach ($data as $key2 => $dt) {?>

                <div class="col">
                    <div class="card shadow-sm">
                        <img class="bd-placeholder-img card-img-top" width="auto" height="225" src="http://<?=$_SERVER['HTTP_HOST']?>/public/images/<?=$dt->getImage()?>">
                        <div class="card-body">
                            <p class="card-header"><?=$dt->getInterpreter()?>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">

                                    <a href="/media/edit/<?=$dt->getId()?>" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Edit</a>
                                    <a href="/media/view/<?=$dt->getId()?>" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">View</a>
                                    <a href="/media/delete/<?=$dt->getId();?>" class="btn btn-sm btn-outline-secondary" role="button" aria-pressed="true">Delete</a>

                                </div>
                                <small class="text-muted">10 mins</small>
                            </div>
                        </div>
                    </div>
                </div>

            <?php } ?>

            </div>


        </div>

    </div>

    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li class="prev-item page-item"><a class="page-link prev" href="http://<?=$_SERVER['HTTP_HOST']?>/media/page/<?=$Paginator->getPrev()?>">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="next-item page-item"><a class="page-link next" href="http://<?=$_SERVER['HTTP_HOST']?>/media/page/<?=$Paginator->getNext();?>">Next</a></li>
        </ul>
    </nav>

</main>

