<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Add new Album example</h1>
                <p>
                    <a href="#" class="btn btn-primary my-2">Main call to action</a>
                    <a href="#" class="btn btn-secondary my-2">Secondary action</a>
                </p>
            </div>
        </div>
    </section>



    <div class="container w-100">

    <div class="row">

        <div class="col">

            <div class="card-header">

            <img class="mr-3"  style="max-width: 200px;" src="../../public/images/<?=$this->viewData['mediaData']->getImage()?>" alt="Generic placeholder image" />

            <div class="form-group">
                <label for="title">ID</label>
                <input type="text" name="id" class="form-control-plaintext" id="id" placeholder="title" value="<?=$this->viewData['mediaData']->getId()?>">
            </div>

            <div class="form-group">
                <label for="mediaType">Media type</label>
                <input type="text" name="type" class="form-control-plaintext" id="mediaType" aria-describedby="mediaHelp" placeholder="type of media" value="<?=$this->viewData['mediaData']->getType()?>">
                <small id="mediaHelp" class="form-text text-muted">Media type (CD, VIDEO, ....)</small>
            </div>
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" name="title" class="form-control-plaintext" id="title" placeholder="title" value="<?=$this->viewData['mediaData']->getTitle()?>">
            </div>
            <div class="form-group">
                <label for="interpreter">Interpreter</label>
                <input type="text" name="interpreter" class="form-control-plaintext" id="interpreter" placeholder="interpreter" value="<?=$this->viewData['mediaData']->getInterpreter()?>">
            </div>
            <div class="form-group">
                <label for="genre">Genre</label>
                <input type="text" name="genre" class="form-control-plaintext" id="genre" placeholder="genre" value="<?=$this->viewData['mediaData']->getGenre()?>">
            </div>
        </div>

    </div>

        <div class="col">

            <div class="card-body" style="background-color: rgba(0,0,0,.03);">
                <div class="form-group;" >
                    <label for="title">title_1</label>
                    <input type="text" name="playlist_title[]" class="form-control-plaintext title"  placeholder="title-1">
                    <label for="duration">duration_1</label>
                    <input type="text" name="playlist_duration[]" class="form-control-plaintext duration"  placeholder="duration-1">
                </div>
            </div>
        </div>

</div>

</div>
</main>
