

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>


<ul class="list-unstyled">

    <a href="media/add" class="btn btn-primary btn-sm active m-4" role="button" aria-pressed="true"> Add New CD Media </a>

    <?php

    foreach($this->viewData['mediaData'] as $key => $dt) { ?>

        <li class="media p-4" style="border: 1px solid; background-color: #d6d8d9;">
            <img class="mr-3"  style="max-width: 200px;" src="public/images/<?=$dt->getImage()?>" alt="Generic placeholder image">
            <div class="media-body">
              <h5 class="mt-0 mb-2"></h5>
                <ul class="list-group w-50">
                    <li class="list-group-item active"><?=$dt->getInterpreter()?></li>
                    <li class="list-group-item">Title: <?=$dt->getTitle()?></li>
                    <li class="list-group-item">  Published: <?=$dt->getPublished()?></li>
                    <li class="list-group-item">Genre: <?=$dt->getGenre()?></li>
                </ul>
            </div>
            <div>
                <a href="media/edit/<?=$dt->getId()?>" class="btn btn-secondary btn active" role="button" aria-pressed="true">Edit</a>
                <a href="media/delete/<?=$dt->getId();?>" class="btn btn-secondary btn active" role="button" aria-pressed="true">Delete</a>
            </div>
        </li>

    <?php } ?>

</ul>


